export const LANGUAGES = {
    en: {
        code: 'en',
        name: 'English',
        nativeName: 'English',
        label: 'EN',
        speechLang: 'en-US',
        bhashiniCode: 'en',
    },
    as: {
        code: 'as',
        name: 'Assamese',
        nativeName: 'অসমীয়া',
        label: 'অ',
        speechLang: 'as-IN',
        bhashiniCode: 'as',
    },
};

export const UI_STRINGS = {
    en: {
        appName: 'MediClear',
        tagline: 'Understand Your Health, Simply.',
        subtitle: 'Upload your medical report and get a clear, friendly explanation — in your language.',
        uploadTitle: 'Upload Your Report',
        uploadSubtitle: 'Take a photo or choose a file',
        takePhoto: 'Take Photo',
        chooseFile: 'Choose File',
        trySample: 'Try a Sample Report',
        analyzing: 'Analyzing Your Report...',
        analyzingSteps: [
            'Reading your document...',
            'Protecting your privacy...',
            'Translating medical terms...',
            'Preparing your health story...',
        ],
        summary: 'Your Health Summary',
        whatThisMeans: 'What This Means For You',
        actionItems: 'Your Next Steps',
        doctorQuestions: 'Questions for Your Doctor',
        glossary: 'Medical Terms Explained',
        askFollowUp: 'Ask About This Report',
        disclaimer: 'This is not a medical diagnosis. Always consult your healthcare provider for clinical decisions.',
        emergency: 'Contact Your Doctor Now',
        listenButton: 'Listen',
        sampleCBC: 'Blood Test (CBC)',
        sampleDiabetes: 'Diabetes Panel',
        sampleDischarge: 'Discharge Summary',
        featPrivacy: 'Privacy First',
        featPrivacyDesc: 'Your personal info is automatically detected and hidden before analysis.',
        featLanguage: 'Your Language',
        featLanguageDesc: 'Get results in English or Assamese — with voice playback.',
        featSimple: 'Simple & Clear',
        featSimpleDesc: 'No medical jargon. Just clear explanations of what your results mean.',
        featDoctor: 'Doctor Ready',
        featDoctorDesc: 'Get personalized questions to ask at your next appointment.',
        chatPlaceholder: 'Ask a question about your report...',
        suggestedQuestions: [
            'Is this result something to worry about?',
            'What should I eat to improve these numbers?',
            'Should I get tested again soon?',
            'What lifestyle changes would help?',
        ],
        routineStatus: 'Looking Good',
        attentionStatus: 'Worth Discussing',
        urgentStatus: 'Talk to Your Doctor',
        yourResults: 'Your Results',
        normalLabel: 'Normal:',
        tapToLearn: 'Tap to learn more',
        tapToCollapse: 'Tap to collapse',
        statusNormal: 'Normal',
        statusSlightlyHigh: 'Slightly High',
        statusSlightlyLow: 'Slightly Low',
        statusHigh: 'High',
        statusLow: 'Low',
        statusCritical: 'Critical',
        privacyBadge: 'Privacy protected',
        personalDetails: 'personal details masked',
        chatSubtext: 'Have a question? Ask in plain language.',
        analyzeAnother: 'Analyze Another Report',
    },
    as: {
        appName: 'মেডিক্লিয়াৰ',
        tagline: 'আপোনাৰ স্বাস্থ্য বুজি পাওক, সহজকৈ।',
        subtitle: 'আপোনাৰ চিকিৎসা প্ৰতিবেদন আপলোড কৰক আৰু আপোনাৰ ভাষাত স্পষ্ট ব্যাখ্যা পাওক।',
        uploadTitle: 'আপোনাৰ ৰিপ\'ৰ্ট আপলোড কৰক',
        uploadSubtitle: 'ফটো তোলক বা ফাইল বাছনি কৰক',
        takePhoto: 'ফটো তোলক',
        chooseFile: 'ফাইল বাছনি কৰক',
        trySample: 'নমুনা ৰিপ\'ৰ্ট চেষ্টা কৰক',
        analyzing: 'আপোনাৰ ৰিপ\'ৰ্ট বিশ্লেষণ কৰি আছে...',
        analyzingSteps: [
            'আপোনাৰ নথি পঢ়ি আছে...',
            'আপোনাৰ গোপনীয়তা সুৰক্ষিত কৰি আছে...',
            'চিকিৎসা শব্দ অনুবাদ কৰি আছে...',
            'আপোনাৰ স্বাস্থ্য কাহিনী প্ৰস্তুত কৰি আছে...',
        ],
        summary: 'আপোনাৰ স্বাস্থ্য সাৰাংশ',
        whatThisMeans: 'এয়া আপোনাৰ বাবে কি অৰ্থ',
        actionItems: 'আপোনাৰ পৰৱৰ্তী পদক্ষেপ',
        doctorQuestions: 'চিকিৎসকক সোধা প্ৰশ্ন',
        glossary: 'চিকিৎসা শব্দৰ ব্যাখ্যা',
        askFollowUp: 'এই ৰিপ\'ৰ্টৰ বিষয়ে সোধক',
        disclaimer: 'এয়া চিকিৎসা ৰোগ নিৰ্ণয় নহয়। ক্লিনিকেল সিদ্ধান্তৰ বাবে সদায় আপোনাৰ স্বাস্থ্যসেৱা প্ৰদানকাৰীৰ সৈতে পৰামৰ্শ কৰক।',
        emergency: 'এতিয়াই চিকিৎসকৰ সৈতে যোগাযোগ কৰক',
        listenButton: 'শুনক',
        sampleCBC: 'তেজৰ পৰীক্ষা (CBC)',
        sampleDiabetes: 'ডায়েবেটিছ পেনেল',
        sampleDischarge: 'ডিচ্চাৰ্জ সাৰাংশ',
        chatPlaceholder: 'আপোনাৰ ৰিপ\'ৰ্টৰ বিষয়ে এটা প্ৰশ্ন সোধক...',
        routineStatus: 'ভাল দেখা গৈছে',
        attentionStatus: 'আলোচনাৰ যোগ্য',
        urgentStatus: 'চিকিৎসকৰ সৈতে কথা পাতক',
        yourResults: 'আপোনাৰ ফলাফল',
        normalLabel: 'সাধাৰণ:',
        tapToLearn: 'অধিক জানিবলৈ টেপ কৰক',
        tapToCollapse: 'সংকুচিত কৰিবলৈ টেপ কৰক',
        statusNormal: 'সাধাৰণ',
        statusSlightlyHigh: 'সামান্য বৃদ্ধি',
        statusSlightlyLow: 'সামান্য হ্ৰাস',
        statusHigh: 'বৃদ্ধি',
        statusLow: 'হ্ৰাস',
        statusCritical: 'জৰুৰী',
        privacyBadge: 'গোপনীয়তা সুৰক্ষিত',
        personalDetails: 'ব্যক্তিগত তথ্য লুকুৱা হৈছে',
        chatSubtext: 'প্ৰশ্ন আছে? সহজ ভাষাত সোধক।',
        analyzeAnother: 'আন এখন ৰিপৰ্ট বিশ্লেষণ কৰক',
    },
};
